version: '2'

services:
    api:
        container_name: sknow_api
        build:
            context: .
            dockerfile: docker/api.Dockerfile
        ports:
            - 5000:5000
        volumes:
            - ./api:/api
        depends_on: 
            - mongodb
        command: sh -c "python api.py"

    mongodb:
        container_name: sknow_db
        image: mongo:4.0.8-xenial
        restart: unless-stopped
        ports:
            - 27017:27017
        volumes:
            - ./data/db:/data/db
        command: mongod --smallfiles --oplogSize 128

